App_Blog/urls.py
from django.urls import path
from . import views

app_name = 'App_Blog'

urlpatterns = [
    path('', views.BlogList.as_view(), name='blogs'),
    path('add_blog/', views.AddBlog.as_view(), name='add_blog'),
    path('details/<slug:blog_slug>/', views.BlogDetail, name='blog_detail'),
]

App_Login/urls.py
from django.urls import path
from . import views

app_name = 'App_Login'

urlpatterns = [
    path('signup/', views.signup_page, name='signup'),
    path('signin/', views.signin_page, name='signin'),
    path('signout/', views.signout_page, name='signout'),
    path('profile/', views.profile_page, name='profile'),
    path('edit_profile/', views.edit_profile_page, name='edit_profile'),
    path('password/', views.change_password_page, name='change_password'),
    path('add_profile_pic/', views.add_profile_picture_page, name='add_profile_pic'),
    path('change_profile_pic/', views.change_profile_picture_page, name='change_profile_pic'),
]

Blog_Site/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf import settings
from django.contrib.staticfiles.urls import static, staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='index'),
    path('blogs/', include('App_Blog.urls')),
    path('accounts/', include('App_Login.urls')),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

App_Login/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

# For User Profile
class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='user_profile')
    profile_pic = models.ImageField(upload_to='profile_pics', blank=True)

App_Login/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.contrib.auth.models import User
from App_Login.models import UserProfile

# For Sign Up
class SignUpForm(UserCreationForm):
    email = forms.EmailField(max_length=100)

    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')



# Edit Profile
class EditProfileForm(UserChangeForm):
    class Meta:
        model = User
        fields = ('username', 'email', 'password')



# Add Profile Picture
class AddProfilePicture(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ('profile_pic',)

App_Login/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth.forms import AuthenticationForm, PasswordChangeForm
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from App_Login.forms import SignUpForm, EditProfileForm, AddProfilePicture


# Create your views here.

# For Sign Up
def signup_page(request):
    form = SignUpForm()

    registered = False
    if request.method == 'POST':
        form = SignUpForm(data=request.POST)
        if form.is_valid():
            form.save()
            registered = True
        else:
            print(form.errors)

    return render(request, 'App_Login/signup.html', {'form': form, 'registered': registered})



# For Sign In
def signin_page(request):
    form = AuthenticationForm()

    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                return HttpResponseRedirect(reverse('App_Login:profile'))
        else:
            print(form.errors)

    return render(request, 'App_Login/signin.html', {'form': form})



# For Sign Out
@login_required
def signout_page(request):
    logout(request)
    return HttpResponseRedirect(reverse('App_Login:signin'))



# For Profile
@login_required
def profile_page(request):
    return render(request, 'App_Login/profile.html')



# For Edit Profile
@login_required
def edit_profile_page(request):
    current_user = request.user
    form = EditProfileForm(instance=current_user)

    if request.method == 'POST':
        form = EditProfileForm(request.POST, instance=current_user)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('App_Login:profile'))
        else:
            print(form.errors)

    return render(request, 'App_Login/edit_profile.html', {'form': form})



# For Change Password
@login_required
def change_password_page(request):
    current_user = request.user
    form = PasswordChangeForm(current_user)

    if request.method == 'POST':
        form = PasswordChangeForm(current_user, data=request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('App_Login:profile'))
        else:
            print(form.errors)

    return render(request, 'App_Login/change_password.html', {'form': form})



# For Add Profile Picture
@login_required
def add_profile_picture_page(request):
    form = AddProfilePicture()

    if request.method == 'POST':
        form = AddProfilePicture(request.POST, request.FILES)
        if form.is_valid():
            user_obj = form.save(commit=False)
            user_obj.user = request.user
            user_obj.save()
            return HttpResponseRedirect(reverse('App_Login:profile'))
        else:
            print(form.errors)

    return render(request, 'App_Login/add_profile_picture.html', {'form': form})



# For Change Profile Picture
@login_required
def change_profile_picture_page(request):
    form = AddProfilePicture(instance=request.user.user_profile)

    if request.method == 'POST':
        form = AddProfilePicture(request.POST, request.FILES, instance=request.user.user_profile)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('App_Login:profile'))
        else:
            print(form.errors)

    return render(request, 'App_Login/add_profile_picture.html', {'form': form})

templates/App_Login/add_profile_picture.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title_block %}{{ title }}{% endblock %}
{% block body_block %}
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form|crispy }}
    <input type="submit" value="Update" class="btn btn-warning">
</form>
{% endblock %}

templates/App_Login/change_password.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title_block %}{{ title }}{% endblock %}
{% block body_block %}
<form method="POST">
    {% csrf_token %}
    {{ form|crispy }}
    <input type="submit" value="Update" class="btn btn-warning">
</form>
{% endblock %}

templates/App_Login/edit_profile.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title_block %}{{ title }}{% endblock %}
{% block body_block %}
<form method="POST">
    {% csrf_token %}
    {{ form|crispy }}
    <input type="submit" value="Update" class="btn btn-warning">
</form>
{% endblock %}

templates/App_Login/profile.html
{% extends 'base.html' %}
{% block title_block %} {{ user.is_authenticated }} {% endblock %}
{% block body_block %}
    {% if user.user_profile %}
    <img src='/media/{{ user.user_profile.profile_pic }}' alt="Profile Pic" width="100">
    <br>
    <a href="{% url 'App_Login:change_profile_pic' %}" class="btn btn-info">Change photo</a>
    {% else %}
    <img src="/media/profile_pics/demo.jpg" alt="Profile Pic"  width="100" >
    <br>
    <a href="{% url 'App_Login:add_profile_pic' %}" class="btn btn-info">Change photo</a>
    {% endif %}
    <p>Username: {{ user.username }}</p>
    <p>Email: {{ user.email }}</p>
    <p>First Name: {{ user.first_name }}</p>
    <p>Last Name: {{ user.last_name }}</p>
    <a href="{% url 'App_Login:edit_profile' %}" class="btn btn-warning">Change info</a>
{% endblock %}

templates/App_Login/signin.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title_block %} Sign in {% endblock %}
{% block body_block %}
<form method="POST">
    {% csrf_token %}
    {{ form|crispy }}
    <button type="submit" class="btn btn-primary">Sign in</button>
</form>
{% endblock %}

templates/App_Login/signup.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title_block %} Sign up {% endblock %}
{% block body_block %}
{% if registered %}
<div class="alert alert-success">
    <p>Registration successfull. <a href="{% url 'App_Login:signin' %}">Sign in</a></p>
</div>
{% else %}
    <h3>Sign up</h3>
    <form method="post">
        {% csrf_token %}
        {{ form|crispy }}
        <input type="submit" value="Sign up" class="btn btn-primary">
    </form>
{% endif %}
{% endblock %}