App_Blog/urls.py
from django.urls import path
from . import views

app_name = 'App_Blog'

urlpatterns = [
    path('', views.BlogList.as_view(), name='blogs'),
    path('add_blog/', views.AddBlog.as_view(), name='add_blog'),
    path('details/<slug:blog_slug>/', views.BlogDetail, name='blog_detail'),
]

App_Login/urls.py
from django.urls import path
from . import views

app_name = 'App_Login'

urlpatterns = [
    path('signup/', views.signup_page, name='signup'),
    path('signin/', views.signin_page, name='signin'),
    path('signout/', views.signout_page, name='signout'),
    path('profile/', views.profile_page, name='profile'),
    path('edit_profile/', views.edit_profile_page, name='edit_profile'),
    path('password/', views.change_password_page, name='change_password'),
    path('add_profile_pic/', views.add_profile_picture_page, name='add_profile_pic'),
    path('change_profile_pic/', views.change_profile_picture_page, name='change_profile_pic'),
]

Blog_Site/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf import settings
from django.contrib.staticfiles.urls import static, staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='index'),
    path('blogs/', include('App_Blog.urls')),
    path('accounts/', include('App_Login.urls')),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title_block %} Page title {% endblock %}</title>
    <link rel="icon" type="/media/images/Favicon.ico" href="/media/images/Favicon.ico">
    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <!-- Bootstrap JS -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <!-- Custom CSS -->
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
              <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                  <li class="nav-item">
                      <a class="nav-link active" aria-current="page" href="{% url 'App_Blog:blogs' %}"><img src="/media/images/Logo.png" alt="Logo" width='50'></a>
                  </li>
                  {% if user.is_authenticated %}
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'App_Blog:add_blog' %}">Add Blog</a>
                  </li>
                  <li class="nav-item">
                      <a class="nav-link" href="{% url 'App_Login:profile' %}">Profile</a>
                  </li>
                  <li class="nav-item">
                      <a class="nav-link" href="{% url 'App_Login:signout' %}">Logout</a>
                  </li>
                  {% else %}
                  <li class="nav-item">
                      <a class="nav-link" href="{% url 'App_Login:signin' %}">Sign in</a>
                  </li>
                  <li class="nav-item">
                      <a class="nav-link" href="{% url 'App_Login:signup' %}">Sign up</a>
                  </li>
                  {% endif %}
              </ul>
            </div>
        </div>
      </nav>
    <div class="container py-5">
        {% block body_block %}

        {% endblock %}
    </div>
</body>
</html>